### ISSUE TITLE
Add tomcat legacy as a test case for analysis

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/go-konveyor-tests#31]
https://github.com/konveyor/example-applications/tree/main/example-1

**Comment by aufi** [comment]
Test was updated with fixes of incidents line numbers and Tags. Currently expected analysis results is at https://github.com/konveyor/go-konveyor-tests/blob/main/analysis/tc_tackle_testapp_public.go

@dymurray @pranavgaikwad I'd like to review&confirm if expected analysis results is correct, thanks!

Open questions for the analysis results approval:
- Tags contains duplicates (e.g. Servlet or Properties - https://github.com/konveyor/go-konveyor-tests/blob/main/analysis/tc_tackle_testapp_public.go#L187-L199), is this a bug?
- Incidents line numbers were shifted by 1 with last update, example https://gist.github.com/aufi/6c3e8e931982e1cc2c706c115a94acbf#file-output-log-L11-L12 is it OK?
- Some dependencies versions look strange e.g. ```${spring-framework.version}``` example https://github.com/konveyor/go-konveyor-tests/blob/main/analysis/tc_tackle_testapp_public.go#L94-L158 is this expected?

**Comment by mguetta1** [comment]
> * Some dependencies versions look strange e.g. `${spring-framework.version}` example https://github.com/konveyor/go-konveyor-tests/blob/main/analysis/tc_tackle_testapp_public.go#L94-L158 is this expected? No. Likely a bug.

https://issues.redhat.com/browse/MTA-1283

**Comment by aufi** [comment]
Basic TestAppPublic analysis test (just source) is now part of TIER0.
